# Generated by Django 5.2.11 on 2026-02-08 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_name', models.CharField(max_length=50)),
                ('start_point', models.CharField(max_length=50)),
                ('end_point', models.CharField(max_length=50)),
                ('distance_km', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
