# Generated by Django 5.2.11 on 2026-02-08 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=20, unique=True)),
                ('model', models.CharField(max_length=50)),
                ('capacity', models.PositiveIntegerField(help_text='Number of passengers')),
                ('status', models.CharField(choices=[('Available', 'Available'), ('In Service', 'In Service'), ('Out of Service', 'Out of Service')], default='Available', max_length=20)),
            ],
        ),
    ]
