# Generated by Django 5.2.11 on 2026-02-09 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers_app', '0001_initial'),
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='driver_name',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='passengers',
        ),
        migrations.AddField(
            model_name='trip',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='drivers_app.driver'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='revenue_collected',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
